### PR TITLE
Fox grid2

### PR DESCRIPTION
**Pull request by janrohlicek**
Re-worked Fox Grid interfaces

### CODE REVIEW

**Comment by vincefn** [comment]
Is this working under windows when creating a job from an xml file ? I could not make this work under macOS - the job window creation remains stuck as if the number of trials provided was zero regardless of the number given.

**Comment by janrohlicek** [comment]
> Is this working under windows when creating a job from an xml file ? I could not make this work under macOS - the job window creation remains stuck as if the number of trials provided was zero regardless of the number given.

Hi, it works well under windows. Strange, that it does not work under MacOS. I will check for possible errors...

**Comment by vincefn** [comment]
Could you also merge back the main branch into this one ? There's a conflict with the visual c++ project file (now that I merged the ssNMR branch), it's likely better if you do this merge.

**Comment by vincefn** [comment]
OK, I found the issue when editing a job: you are using `ToLong((long * ) &trials)` (where `trials` is an int), which is incorrect- on windows it's OK as both `int` and `long` are 32-bit, but this does not work under linux or macOS (int is 32-bit, long 64, see https://www.ccoderun.ca/programming/2017-03-10_sizeof/).

Using `ToInt()` instead solves this. I removed all int->long pointer casting.

**Comment by vincefn** [comment]
@janrohlicek OK, I should have fixed the compilation on macOS and linux. I let you check if everything is still OK under windows, then I will merge.

I has some issues starting the local client in macOS, it was not always working, not yet sure why. otherwise looks good !

**Comment by janrohlicek** [comment]
Hi, I apologize, I was out of PC during the weekend. Both, client and master search free ports for communication. They check it using the GridCommunication::getUsedPorts(). This function uses netstat -an command to get the info about free ports. Isnt that the source of troubles under macOS?

**Comment by vincefn** [comment]
> Hi, I apologize, I was out of PC during the weekend. Both, client and master search free ports for communication. They check it using the GridCommunication::getUsedPorts(). This function uses netstat -an command to get the info about free ports. Isnt that the source of troubles under macOS?

I don't know - it did not work a few times, and then it did - I am not sure why. Maybe there was still a Fox client leftover, and that created an issue. I'll do some more tests when I have the time, but don't worry about it.

Can you test if the code works for you correctly under windows correctly (also the parts coming from inter-molecular restraints). If yes, I'll merge the code, and can start preparing a release (or maybe beta release) by the end of the week so it's available for you at EPDIC.

**Comment by janrohlicek** [comment]
I just finished testing on 3 PCs in the network and it works. Also the ssNMR functionality works. Great!:)

**Pull request merged**
